---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: minio
  name: minio
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args: 
    - minio server /data --console-address :9090
    volumeMounts:
    - mountPath: /data
      name: datavolume
  volumes:
  - name: datavolume
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app.kubernetes.io/name: minio
  ports:
    - protocol: TCP
      port: 9090
      name: console
      targetPort: 9090
    - protocol: TCP
      port: 9000
      name: api
      targetPort: 9000
